import type { PackTemplate } from "@/types/domain";

/**
 * AI Engineering pack = suggestion + defaults + fixed diagnostic bank only.
 * All stages/modules/lessons are still generated by Pathforge AI at runtime.
 */
export const AI_ENGINEERING_PACK: PackTemplate = {
  slug: "ai-engineering",
  title: "AI Engineering",
  description:
    "Build real AI systems: foundations, ML intuition, LLMs, RAG, agents, and production habits. Path content is generated for you after a short placement quiz.",
  intakeDefaults: {
    topic: "AI Engineering",
    goal: "Become productive building AI-powered products (agents, RAG, applied ML)",
    hoursPerWeek: 6,
  },
  diagnosticBank: [
    {
      id: "ae-1",
      prompt: "What does overfitting usually look like?",
      choices: [
        "High training error, high test error",
        "Low training error, high test error",
        "Low training error, low test error",
        "Model cannot fit the training set at all",
      ],
      correctIndex: 1,
      skillTag: "ml-fundamentals",
    },
    {
      id: "ae-2",
      prompt: "A good validation split is mainly used to…",
      choices: [
        "Train faster on GPUs",
        "Estimate generalization and tune decisions without touching the final test set",
        "Increase the number of features",
        "Remove the need for regularization",
      ],
      correctIndex: 1,
      skillTag: "ml-fundamentals",
    },
    {
      id: "ae-3",
      prompt: "In a Transformer, self-attention primarily lets the model…",
      choices: [
        "Only look at the previous token",
        "Weight relationships between tokens in the sequence",
        "Replace all need for data",
        "Guarantee factual correctness",
      ],
      correctIndex: 1,
      skillTag: "transformers",
    },
    {
      id: "ae-4",
      prompt: "RAG (retrieval-augmented generation) is most useful when…",
      choices: [
        "You need the model to invent new math proofs",
        "You want answers grounded in your documents or fresh external knowledge",
        "You want to avoid all embeddings",
        "You only do image classification",
      ],
      correctIndex: 1,
      skillTag: "rag",
    },
    {
      id: "ae-5",
      prompt: "Temperature in LLM decoding mainly controls…",
      choices: [
        "Context window size",
        "How peaked vs random the next-token distribution is",
        "Embedding dimensionality",
        "Number of attention heads",
      ],
      correctIndex: 1,
      skillTag: "llm-api",
    },
    {
      id: "ae-6",
      prompt: "A simple agent loop typically includes…",
      choices: [
        "Train from scratch every request",
        "Plan/act with tools, observe results, repeat until done",
        "Only one static prompt with no tools",
        "Manual SQL only",
      ],
      correctIndex: 1,
      skillTag: "agents",
    },
    {
      id: "ae-7",
      prompt: "Embeddings are vectors used mainly to…",
      choices: [
        "Compress images for JPEG",
        "Represent meaning so similar items are close in space",
        "Replace authentication",
        "Schedule cron jobs",
      ],
      correctIndex: 1,
      skillTag: "embeddings",
    },
    {
      id: "ae-8",
      prompt: "Which is a production concern for LLM apps?",
      choices: [
        "Prompt injection, evals, cost/latency, observability",
        "Only picking a prettier font",
        "Deleting all logs",
        "Avoiding version control",
      ],
      correctIndex: 0,
      skillTag: "production",
    },
    {
      id: "ae-9",
      prompt: "Fine-tuning is often NOT the first lever when…",
      choices: [
        "You need the model to follow a brand new domain style and prompting + RAG already fail after serious iteration",
        "You can solve the task with better prompts, tools, or retrieved context",
        "You have millions of labeled examples and a clear metric",
        "You are building a specialist speech model",
      ],
      correctIndex: 1,
      skillTag: "finetune",
    },
    {
      id: "ae-10",
      prompt: "Chunking documents for RAG matters because…",
      choices: [
        "It only affects CSS",
        "Chunk size/overlap change what gets retrieved and how coherent context is",
        "Models ignore retrieved text",
        "It removes the need for embeddings",
      ],
      correctIndex: 1,
      skillTag: "rag",
    },
  ],
};

export const PACKS: Record<string, PackTemplate> = {
  [AI_ENGINEERING_PACK.slug]: AI_ENGINEERING_PACK,
};

export function getPack(slug: string): PackTemplate | null {
  return PACKS[slug] ?? null;
}

export function listPacks(): PackTemplate[] {
  return Object.values(PACKS);
}
