import Link from "next/link";
import { listPacks } from "@/lib/packs/ai-engineering";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export default function HomePage() {
  const packs = listPacks();

  return (
    <div className="mx-auto max-w-5xl px-4 py-16">
      <section className="mx-auto max-w-2xl text-center">
        <p className="mb-3 text-sm font-medium text-teal-700 dark:text-teal-300">
          Learn anything with a path that remembers you
        </p>
        <h1 className="text-4xl font-semibold tracking-tight sm:text-5xl">
          Your personal curriculum, forged by AI
        </h1>
        <p className="mt-4 text-lg text-zinc-600 dark:text-zinc-400">
          Pathforge builds a staged roadmap for whatever you want to learn,
          then teaches module-by-module with short lesson cards, real web
          resources, progress, and a grounded tutor — without generating an
          entire course up front.
        </p>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <Link
            href="/login"
            className="inline-flex h-12 items-center rounded-xl bg-teal-600 px-6 text-base font-medium text-white hover:bg-teal-500"
          >
            Get started
          </Link>
          <Link
            href="/paths/new"
            className="inline-flex h-12 items-center rounded-xl border border-zinc-300 px-6 text-base font-medium hover:bg-zinc-100 dark:border-zinc-700 dark:hover:bg-zinc-900"
          >
            Start a path
          </Link>
        </div>
      </section>

      <section className="mt-20 grid gap-4 sm:grid-cols-3">
        {[
          {
            t: "Generate",
            d: "Intake + diagnostic → personalized stages (L0), then modules on demand.",
          },
          {
            t: "Guide & teach",
            d: "Today’s next module, short cards, optional quiz, module-scoped tutor.",
          },
          {
            t: "Curate",
            d: "Serper-backed links (and YouTube when configured) — cached forever.",
          },
        ].map((f) => (
          <Card key={f.t}>
            <CardHeader>
              <CardTitle>{f.t}</CardTitle>
              <CardDescription>{f.d}</CardDescription>
            </CardHeader>
          </Card>
        ))}
      </section>

      <section className="mt-16">
        <h2 className="mb-4 text-xl font-semibold">Suggested pack</h2>
        <div className="grid gap-4">
          {packs.map((pack) => (
            <Card key={pack.slug}>
              <CardHeader>
                <CardTitle>{pack.title}</CardTitle>
                <CardDescription>{pack.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <Link
                  href={`/paths/new?pack=${pack.slug}`}
                  className="inline-flex h-10 items-center rounded-lg bg-teal-600 px-4 text-sm font-medium text-white hover:bg-teal-500"
                >
                  Start {pack.title}
                </Link>
                <p className="mt-3 text-xs text-zinc-500">
                  Pack sets defaults + placement quiz only. Every lesson is
                  still generated by Pathforge AI for you.
                </p>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>
    </div>
  );
}
